version: '3.8'

services:
  django:
    # Берем Dockerfile из ./docker/django/
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: genealogy_django
    container_name: genealogy_django
    # Определяем внешние тома (volume) и места, где они будут подключены внутри контейнера
    volumes:
      - genealogy_static:/genealogy/static
      - genealogy_media:/genealogy/media
      - genealogy_fixtures:/genealogy/fixtures_temp
    # Открываем порт 8050 внутри
    expose:
      - "8050"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres
    # Собираем статику, делаем миграции и запускаем WSGI
    command: sh -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn backend.wsgi -b 0.0.0.0:8050"

  postgres:
    restart: always
    build:
      context: ./docker/postgres/
      dockerfile: ./Dockerfile
    image: genealogy_postgres
    container_name: genealogy_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - genealogy_postgres:/var/lib/postgresql/data/

  nginx:
    restart: always
    build:
      context: ./docker/nginx/
      dockerfile: ./Dockerfile
    image: genealogy_nginx
    container_name: genealogy_nginx
    ports:
      - "85:85"
    volumes:
      - genealogy_static:/genealogy/static
      - genealogy_media:/genealogy/media
      - genealogy_fixtures:/genealogy/fixtures
    depends_on:
      - django

volumes:
  genealogy_postgres:
  genealogy_static:
  genealogy_media:
  genealogy_fixtures:
